version: "3.5"
services:
  python:
    build: .
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - ${APP_PORT}:8000
    command: python3.9 manage.py runserver 0.0.0.0:8000
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
