# Generated by Django 4.0 on 2022-02-24 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('employee_views', 'Can enter employee views'),
                                     ('client_views', 'Can enter client views')
                                     ]},
        ),
    ]
