# Generated by Django 4.0 on 2022-01-11 19:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rented_to', models.DateTimeField(null=True)),
                ('rented_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rents', to='core.user')),
                ('rented_car', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rent', to='car.car')),
            ],
        ),
    ]
