# Generated by Django 4.0 on 2022-02-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily', models.PositiveIntegerField()),
                ('weekly', models.PositiveIntegerField()),
                ('monthly', models.PositiveIntegerField()),
            ],
        ),
    ]
