# Generated by Django 4.0 on 2022-06-08 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_availability_car_alter_scheduleservice_car'),
        ('rent', '0002_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='rented_car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='car.car'),
        ),
    ]
