# Generated by Django 4.0 on 2022-06-08 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_availability_car_alter_scheduleservice_car'),
        ('log', '0002_messagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlog',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='car.car'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='car.car'),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='car.car'),
        ),
    ]
