# Generated by Django 4.0 on 2022-02-21 21:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rent', '0002_pricing'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pricing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car',
                                    to='rent.pricing'),
        ),
        migrations.AlterField(
            model_name='car',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
