# Generated by Django 4.0 on 2022-02-22 20:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_pricing_alter_car_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_mileage_interval', models.PositiveIntegerField(default=15000)),
                ('insured_date', models.DateField(default=django.utils.timezone.now)),
                ('technical_overview_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='insured_date',
        ),
        migrations.RemoveField(
            model_name='car',
            name='service_mileage_interval',
        ),
        migrations.RemoveField(
            model_name='car',
            name='technical_overview_date',
        ),
        migrations.AddField(
            model_name='car',
            name='servicing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='car', to='car.servicing'),
        ),
    ]
