# Generated by Django 4.0 on 2022-02-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('car', '0003_servicing_remove_car_insured_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
