# Generated by Django 4.0 on 2022-06-08 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usercarpickupaddress'),
        ('car', '0004_companycar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.usercarpickupaddress')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='availabilities', to='car.car')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
