# Generated by Django 4.0 on 2022-06-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end',
            field=models.DateTimeField(),
        ),
    ]
