# Generated by Django 4.0 on 2022-06-08 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_scheduleservice_availability_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='car.car'),
        ),
        migrations.AlterField(
            model_name='scheduleservice',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_services', to='car.car'),
        ),
    ]
