name: Build, migrate, type check, test, style check, security check

on:
    push

env:
    APP_SECRET: ${{ secrets.APP_SECRET }}

jobs:
    build:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
                    MYSQL_DATABASE: ${{ secrets.DATABASE_NAME }}
                ports: [ '3306:3306' ]
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python $
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9
            -   name: Install Dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            -   name: Run Migrations
                run: python manage.py migrate
            -   name: Type check
                run: mypy .
            -   name: Tests
                run: python3.9 manage.py test
            -   name: Style check
                run: flake8 --max-line-length 120 --exclude node_modules,migrations,venv
            -   name: Security check
                run: bandit -r . --exclude /tests,./node_modules,/core/services/os_service.py,/venv
